version: '3.8'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: db-container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
  api:
    container_name: api-container
    build: ./backEnd
    ports:
      - "8080:80"
    depends_on:
      - db





  # todo-ui:
  #   build: ./frontEnd
  #   container_name: todo-ui
  #   ports:
  #     - 4200:80
  #   links:
  #     - todo-api
  
  # todo-api:
  #   build: ./backend
  #   container_name: todo-api
  #   ports:
  #     - 8080:80
  #   environment:
  #     DB_CONNECTION_STRING: "Data Source=DESKTOP-CJ4PCSB;Initial Catalog=TodoApp;Integrated Security=True;Trust Server Certificate=true"